import { chromium } from "/home/user/DevUP/node_modules/playwright/index.mjs";
const [email,password,orgId,out]=process.argv.slice(2);
const errs=[]; const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome"});
const p=await (await b.newContext({viewport:{width:1280,height:800}})).newPage();
p.on("pageerror",e=>errs.push("pageerror: "+String(e).slice(0,180)));
p.on("console",m=>{if(m.type()==="error"&&!m.text().includes("401"))errs.push("console: "+m.text().slice(0,180));});
await p.goto("http://localhost:3000/login"); await p.waitForTimeout(4000);
await p.fill('input[type="email"]',email); await p.fill('input[type="password"]',password);
await p.click('button[type="submit"]');
await p.waitForFunction(()=>location.pathname.startsWith("/app"),{timeout:20000});
await p.goto(`http://localhost:3000/app/o/${orgId}/ventas`);
await p.waitForTimeout(3500);
const body=(await p.textContent("body"))||"";
console.log("columnas del embudo:", ["Contacto","Cualificada","Propuesta","Ganada","Perdida"].filter(s=>body.includes(s)).length, "de 5");
console.log("resumen:", /([\d.,]+\s*€)[^€]*en el embudo abierto/.exec(body)?.[0] ?? "(no encontrado)");
console.log("venta en pantalla:", body.includes("Migración del backend")?"sí":"NO");
await p.screenshot({path: out+"/embudo.png"});
console.log(errs.length?"ERRORES:\n"+errs.join("\n"):"sin errores de consola");
await b.close();
